repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-rnaseq-nf_logo_light.png
    - docs/images/nf-core-rnaseq-nf_logo_light.png
    - docs/images/nf-core-rnaseq-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config: false
  multiqc_config:
    - report_comment
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - nextflow_schema.json
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - nextflow_schema.json
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-rnaseq-nf_logo_light.png
    - docs/images/nf-core-rnaseq-nf_logo_light.png
    - docs/images/nf-core-rnaseq-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: tyfu-cc
  name: rnaseq-nf
  description: A RNA-seq pipeline
  author: Tianyi Fu
  version: 0.1.0
  force: true
  outdir: .
  skip_features:
    - ci
    - igenomes
    - github_badges
    - code_linters
    - citations
    - gitpod
    - codespaces
    - nf_schema
    - slackreport
    - test_config
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
